apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whisper.fullname" . }}
  labels:
    {{- include "whisper.labels" . | nindent 4 }}
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: {{ .Values.oauth.clientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.oauth.clientSecret | quote }}
  WHISPER_ALLOWED_EMAILS: {{ .Values.oauth.allowedEmails | quote }}
